### ISSUE TITLE
Error 503 com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes

### ISSUE THREAD

**Issue by virtual-life** [neo4j-contrib/authentication-extension#13]
Hi,

Using neo4j 1.9.2 
I copied the jars file and added the two lines to the neo4j-server.properties file as per the instructions in https://github.com/neo4j-contrib/authentication-extension#basic-auth-filter-extension-for-neo4j-server

I get the following error when I run : 

curl --user user:password http://server_name:7474/auth/list

Error 503 com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes

HTTP ERROR 503
<p>Problem accessing /admin/add-user-rw. Reason:

<pre>    com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.</pre></p><h3>Caused by:</h3><pre>javax.servlet.UnavailableException: com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
    at org.mortbay.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:415)
    at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:458)
    at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
    at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
    at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
    at org.mortbay.jetty.Server.doStart(Server.java:224)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.neo4j.server.web.Jetty6WebServer.startJetty(Jetty6WebServer.java:338)
    at org.neo4j.server.web.Jetty6WebServer.start(Jetty6WebServer.java:162)
    at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:348)
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:183)
    at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:86)
    at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:49)
</pre>

<hr /><i><small>Powered by Jetty://</small></i><br/>

**Comment by jexp** [comment]
Could you share the log in data/log/\* esp. the startup sequence from jetty / jersey where it mounts the resources.

**Comment by virtual-life** [comment]
Below is the log info:

Oct 30, 2013 7:04:01 PM org.neo4j.server.logging.Logger log
INFO: Neo4j Server shutdown initiated by kill signal
Oct 30, 2013 7:04:03 PM org.neo4j.server.logging.Logger log
INFO: Setting startup timeout to: 120000ms based on -1
Oct 30, 2013 7:04:04 PM org.neo4j.server.logging.Logger log
INFO: Successfully started database
Oct 30, 2013 7:04:04 PM org.neo4j.server.logging.Logger log
INFO: Starting Neo Server on port [7474] with [20] threads available
Oct 30, 2013 7:04:04 PM org.neo4j.server.logging.Logger log
INFO: Enabling HTTPS on port [7473]
Oct 30, 2013 7:04:05 PM org.neo4j.server.logging.Logger log
INFO: Mounted discovery module at [/]
Oct 30, 2013 7:04:05 PM org.neo4j.server.logging.Logger log
INFO: Loaded server plugin "CypherPlugin"
Oct 30, 2013 7:04:05 PM org.neo4j.server.logging.Logger log
INFO: Loaded server plugin "GremlinPlugin"
Oct 30, 2013 7:04:05 PM org.neo4j.server.logging.Logger log
INFO: Mounted REST API at [/db/data/]
Oct 30, 2013 7:04:05 PM org.neo4j.server.logging.Logger log
INFO: Mounted management API at [/db/manage/]
Oct 30, 2013 7:04:05 PM org.neo4j.server.logging.Logger log
INFO: Mounted third-party JAX-RS package [org.neo4j.server.extension.auth] at [/admin]
Oct 30, 2013 7:04:05 PM org.neo4j.server.logging.Logger log
INFO: Mounted webadmin at [/webadmin]
Oct 30, 2013 7:04:05 PM org.neo4j.server.logging.Logger log
INFO: Mounting static content at [/webadmin] from [webadmin-html]
Oct 30, 2013 7:04:06 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
Oct 30, 2013 7:04:06 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
Oct 30, 2013 7:04:07 PM com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  org.neo4j.server.extension.auth
Oct 30, 2013 7:04:07 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
Oct 30, 2013 7:04:07 PM com.sun.jersey.server.impl.application.RootResourceUriRules <init>
SEVERE: The ResourceConfig instance does not contain any root resource classes.
Oct 30, 2013 7:04:07 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
Oct 30, 2013 7:04:07 PM org.neo4j.server.logging.Logger log
INFO: Server started on [http://0.0.0.0:7474/]

Thanks

**Comment by virtual-life** [comment]
Just an update. Works perfectly fine with neo4j 1.9.4 though.
