### ISSUE TITLE
Startup error in neo4j-community-2.0.0

### ISSUE THREAD

**Issue by kalliopeargentina** [neo4j-contrib/authentication-extension#18]
Hi, I downloaded the compiled version of the plugin and the I compiled it myself but I still get the same error. any sugestions?

START class org.neo4j.server.extension.auth.AuthenticationExtensionInitializer
2014-01-05 23:58:51.179+0000 DEBUG [API]
org.neo4j.server.ServerStartupException: Starting Neo4j Server failed: Found interface org.neo4j.server.database.Database, but class was expected
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:209) ~[neo4j-server-2.0.0.jar:2.0.0]
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:87) [neo4j-server-2.0.0.jar:2.0.0]
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:50) [neo4j-server-2.0.0.jar:2.0.0]
Caused by: java.lang.IncompatibleClassChangeError: Found interface org.neo4j.server.database.Database, but class was expected
        at org.neo4j.server.extension.auth.AuthenticationExtensionInitializer.start(AuthenticationExtensionInitializer.java:77) ~[authentication-extension-1.9.2-1.0-SNAPSHOT.jar:1.9.2-1.0-SNAPSHOT]
        at org.neo4j.server.modules.ExtensionInitializer.initializePackages(ExtensionInitializer.java:60) ~[neo4j-server-2.0.0.jar:2.0.0]
        at org.neo4j.server.modules.ThirdPartyJAXRSModule.start(ThirdPartyJAXRSModule.java:61) ~[neo4j-server-2.0.0.jar:2.0.0]
        at org.neo4j.server.AbstractNeoServer.startModules(AbstractNeoServer.java:296) ~[neo4j-server-2.0.0.jar:2.0.0]
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:174) ~[neo4j-server-2.0.0.jar:2.0.0]
        ... 2 common frames omitted
2014-01-05 23:58:51.180+0000 DEBUG [API] Failed to start Neo Server on port [7474]

**Comment by jexp** [comment]
You used the wrong branch, use the 2.0 branch

**Comment by kalliopeargentina** [comment]
Sorry, my mistake.

**Comment by jexp** [comment]
Switch to 2.0.1 don't stay with 2.0-M05

**Comment by pradeepmurthy** [comment]
Hi, 
I tried with all available jars, but getting error as below
Im using Neo4j 2.0.1
Please suggest.

---

2014-06-09 09:04:35.083+0000 DEBUG [API]
org.neo4j.server.ServerStartupException: Starting Neo4j Server failed: org.neo4j.server.configuration.Configurator.getThirdpartyJaxRsPackages()Ljava/util/List;
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:218) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:87) [neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:50) [neo4j-server-2.0.1.jar:2.0.1]
Caused by: java.lang.NoSuchMethodError: org.neo4j.server.configuration.Configurator.getThirdpartyJaxRsPackages()Ljava/util/List;
        at org.neo4j.server.extension.auth.AuthenticationExtensionInitializer.getMyMountpoint(AuthenticationExtensionInitializer.java:101) ~[authentication-extension-2.0.2-1.0-SNAPSHOT.jar:2.0.2-1.0-SNAPSHOT]
        at org.neo4j.server.extension.auth.AuthenticationExtensionInitializer.start(AuthenticationExtensionInitializer.java:82) ~[authentication-extension-2.0.2-1.0-SNAPSHOT.jar:2.0.2-1.0-SNAPSHOT]
        at org.neo4j.server.modules.ExtensionInitializer.initializePackages(ExtensionInitializer.java:60) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.modules.ThirdPartyJAXRSModule.start(ThirdPartyJAXRSModule.java:61) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.AbstractNeoServer.startModules(AbstractNeoServer.java:310) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:183) ~[neo4j-server-2.0.1.jar:2.0.1]
        ... 2 common frames omitted
2014-06-09 09:04:35.083+0000 DEBUG [API] Failed to start Neo Server on port [7474]

---

2014-06-09 09:11:23.676+0000 INFO  [API] Setting startup timeout to: 120000ms based on -1
Detected incorrectly shut down database, performing recovery..
2014-06-09 09:11:25.972+0000 INFO  [API] Successfully started database
2014-06-09 09:11:26.830+0000 INFO  [API] Starting HTTP on port :7474 with 80 threads available
2014-06-09 09:11:27.192+0000 INFO  [API] Mounted discovery module at [/]
2014-06-09 09:11:27.200+0000 INFO  [API] Mounted REST API at [/db/data/]
2014-06-09 09:11:27.204+0000 INFO  [API] Mounted management API at [/db/manage/]
2014-06-09 09:11:27.205+0000 INFO  [API] START class org.neo4j.server.extension.auth.AuthenticationExtensionInitializer
2014-06-09 09:11:27.213+0000 DEBUG [API]
org.neo4j.server.ServerStartupException: Starting Neo4j Server failed: Found interface org.neo4j.server.database.Database, but class was expected
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:218) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:87) [neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:50) [neo4j-server-2.0.1.jar:2.0.1]
Caused by: java.lang.IncompatibleClassChangeError: Found interface org.neo4j.server.database.Database, but class was expected
        at org.neo4j.server.extension.auth.AuthenticationExtensionInitializer.start(AuthenticationExtensionInitializer.java:77) ~[authentication-extension-1.9.2-1.0-SNAPSHOT.jar:1.9.2-1.0-SNAPSHOT]
        at org.neo4j.server.modules.ExtensionInitializer.initializePackages(ExtensionInitializer.java:60) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.modules.ThirdPartyJAXRSModule.start(ThirdPartyJAXRSModule.java:61) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.AbstractNeoServer.startModules(AbstractNeoServer.java:310) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:183) ~[neo4j-server-2.0.1.jar:2.0.1]
        ... 2 common frames omitted

---

2014-06-09 09:11:27.214+0000 DEBUG [API] Failed to start Neo Server on port [7474]
2014-06-09 09:18:12.673+0000 INFO  [API] Setting startup timeout to: 120000ms based on -1
Detected incorrectly shut down database, performing recovery..
2014-06-09 09:18:15.018+0000 INFO  [API] Successfully started database
2014-06-09 09:18:15.890+0000 INFO  [API] Starting HTTP on port :7474 with 80 threads available
2014-06-09 09:18:16.287+0000 INFO  [API] Mounted discovery module at [/]
2014-06-09 09:18:16.293+0000 INFO  [API] Mounted REST API at [/db/data/]
2014-06-09 09:18:16.296+0000 INFO  [API] Mounted management API at [/db/manage/]
2014-06-09 09:18:16.297+0000 INFO  [API] START class org.neo4j.server.extension.auth.AuthenticationExtensionInitializer
2014-06-09 09:18:16.304+0000 DEBUG [API]
org.neo4j.server.ServerStartupException: Starting Neo4j Server failed: Found interface org.neo4j.server.database.Database, but class was expected
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:218) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:87) [neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:50) [neo4j-server-2.0.1.jar:2.0.1]
Caused by: java.lang.IncompatibleClassChangeError: Found interface org.neo4j.server.database.Database, but class was expected
        at org.neo4j.server.extension.auth.AuthenticationExtensionInitializer.start(AuthenticationExtensionInitializer.java:77) ~[authentication-extension-1.9-SNAPSHOT-1.0-SNAPSHOT.jar:1.9-SNAPSHOT-1.0-SNAPSHOT]
        at org.neo4j.server.modules.ExtensionInitializer.initializePackages(ExtensionInitializer.java:60) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.modules.ThirdPartyJAXRSModule.start(ThirdPartyJAXRSModule.java:61) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.AbstractNeoServer.startModules(AbstractNeoServer.java:310) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:183) ~[neo4j-server-2.0.1.jar:2.0.1]
        ... 2 common frames omitted

**Comment by TommyJams** [comment]
Hi,

Did someone manage to fix this? I am getting a similar error on Azure with Neo4j, here is the stack trace and log details:

2014-08-10 15:56:38.861+0000 DEBUG [API]
org.neo4j.server.ServerStartupException: Starting Neo4j Server failed: org.neo4j.server.configuration.Configurator.getThirdpartyJaxRsPackages()Ljava/util/List;
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:218) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:87) [neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:50) [neo4j-server-2.0.1.jar:2.0.1]
Caused by: java.lang.NoSuchMethodError: org.neo4j.server.configuration.Configurator.getThirdpartyJaxRsPackages()Ljava/util/List;
        at org.neo4j.server.extension.auth.AuthenticationExtensionInitializer.getMyMountpoint(AuthenticationExtensionInitializer.java:101) ~[authentication-extension-2.0.3-1.0-SNAPSHOT.jar:2.0.3-1.0-SNAPSHOT]
        at org.neo4j.server.extension.auth.AuthenticationExtensionInitializer.start(AuthenticationExtensionInitializer.java:82) ~[authentication-extension-2.0.3-1.0-SNAPSHOT.jar:2.0.3-1.0-SNAPSHOT]
        at org.neo4j.server.modules.ExtensionInitializer.initializePackages(ExtensionInitializer.java:60) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.modules.ThirdPartyJAXRSModule.start(ThirdPartyJAXRSModule.java:61) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.AbstractNeoServer.startModules(AbstractNeoServer.java:310) ~[neo4j-server-2.0.1.jar:2.0.1]
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:183) ~[neo4j-server-2.0.1.jar:2.0.1]
        ... 2 common frames omitted
2014-08-10 15:56:38.877+0000 DEBUG [API] Failed to start Neo Server on port [7474]

The server was well and running, but there was a maintenance that happened on Azure
post which the server has stopped working.
