### ISSUE TITLE
how-to build and install

### ISSUE THREAD

**Issue by ikwattro** [neo4j-contrib/authentication-extension#2]
Hi,

I've tried to install your extension into the neo4j 1.8M07 server.

The steps I've done are the following :
- download this repository
- extract
- run `mvn clean package` command
- copy the jar file inside the /plugins directory of the Neo4j server
- add the necessary lines inside the neo4j.server.properties file
- restart the server

When trying to go to http://localhost:7474/admin , I have the following error :

```
HTTP ERROR 503

Problem accessing /admin/. Reason:

    com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
Caused by:

javax.servlet.UnavailableException: com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
    at org.mortbay.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:415)
    at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:458)
    at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
    at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
    at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
    at org.mortbay.jetty.Server.doStart(Server.java:224)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.neo4j.server.web.Jetty6WebServer.startJetty(Jetty6WebServer.java:306)
    at org.neo4j.server.web.Jetty6WebServer.start(Jetty6WebServer.java:163)
    at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:227)
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:114)
    at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:79)
    at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:46)
```

It is the first time I use maven to build something in java, so I'm maybe/surely wrong in the steps.

Can someone give me some tips on how to correctly install this extension.

Thank you

Cheers,

Chris

**Comment by jexp** [comment]
Which lines did you add to server.properties?

**Comment by ikwattro** [comment]
Sorry Sorry Sorry,

I've copy pasted the lines present in the neo4j-server.properties of [this repository](https://github.com/neo4j/authentication-extension/blob/1.8/conf/neo4j-server.properties) but there is a typo in it `oorg.` in place of `org.` .

```
org.neo4j.server.thirdparty_jaxrs_classes=oorg.neo4j.server.extension.auth=/admin

org.neo4j.server.credentials = user:password
```

Sorry to not have detected it before triggering the issue.

Thank you for your quick reaction.
