### ISSUE TITLE
java error with authentication plugin for version 2.0.0-M05

### ISSUE THREAD

**Issue by satya6388** [neo4j-contrib/authentication-extension#23]
Hi
I tried using the authentication plugin downloaded from the github page (for the 2.0 branch). When I try accessing the web admin with my username & password. I get a java error message:

Is this a version-compatibility issue?

The error message:

Problem accessing /webadmin/. Reason:

```
java.lang.Boolean cannot be cast to java.lang.String
```

Caused by:

java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
    at org.neo4j.server.extension.auth.MultipleAuthenticationService.getCredentials(MultipleAuthenticationService.java:59)
    at org.neo4j.server.extension.auth.MultipleAuthenticationService.hasAccess(MultipleAuthenticationService.java:49)
    at org.neo4j.server.extension.auth.AuthenticationFilter.checkAuth(AuthenticationFilter.java:74)
    at org.neo4j.server.extension.auth.AuthenticationFilter.doFilter(AuthenticationFilter.java:56)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.neo4j.server.guard.GuardingRequestFilter.doFilter(GuardingRequestFilter.java:68)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:440)
    at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:322)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:926)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

**Comment by jexp** [comment]
Good question, I looked at the code and actually don't know how that can happen.

As the code in question is:

```
            Object result = properties.getProperty(userKey, "");
            String credentials = (result instanceof Boolean) ? "" : (String) result;
```

**Comment by satya6388** [comment]
I upgraded to 2.0.1. 
Problem solved....
