### ISSUE TITLE
Plugin doesn't work anymore with Neo4j 2.0.2

### ISSUE THREAD

**Issue by hoffmaaxe** [neo4j-contrib/authentication-extension#25]
I updated today my Debian 7.0.4 64bit (Oracle Java 1.7 51) machine to Neo4j 2.0.2 and can't start Neo4j after the update. When I remove the two lines:

```
org.neo4j.server.credentials=username:password
org.neo4j.server.thirdparty_jaxrs_classes=org.neo4j.server.extension.auth=/auth
```

from the server config, the server is starting without any issue but the authentication is gone.
The logfile shows the following exceptions:

```
console.log
```

```
02:38:50.139 [main] INFO  org.neo4j.server.CommunityNeoServer - Setting startup timeout to: 120000ms based on -1
2014-04-15 00:38:51.080+0000 INFO  [API] Successfully started database
2014-04-15 00:38:51.305+0000 INFO  [API] Starting HTTP on port :7474 with 20 threads available
2014-04-15 00:38:51.534+0000 INFO  [API] Mounted discovery module at [/]
2014-04-15 00:38:51.540+0000 INFO  [API] Mounted REST API at [/db/data/]
2014-04-15 00:38:51.543+0000 INFO  [API] Mounted management API at [/db/manage/]
2014-04-15 00:38:51.543+0000 INFO  [API] Mounted third-party JAX-RS package [org.neo4j.server.extension.auth] at [/auth]
2014-04-15 00:38:51.544+0000 INFO  [API] Mounted webadmin at [/webadmin]
2014-04-15 00:38:51.544+0000 INFO  [API] Mounted Neo4j Browser at [/browser]
2014-04-15 00:38:51.590+0000 INFO  [API] Mounting static content at [/webadmin] from [webadmin-html]
2014-04-15 00:38:51.638+0000 INFO  [API] Mounting static content at [/browser] from [browser]
02:38:51.640 [main] WARN  o.e.j.server.handler.ContextHandler - o.e.j.s.ServletContextHandler@1a7035a2{/,null,null} contextPath ends with /
02:38:51.640 [main] WARN  o.e.j.server.handler.ContextHandler - Empty contextPath
02:38:51.642 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.0.5.v20130815
02:38:51.672 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.h.MovedContextHandler@67697fca{/,null,AVAILABLE}
02:38:51.756 [main] INFO  o.e.j.w.StandardDescriptorProcessor - NO JSP Support for /webadmin, did not find org.apache.jasper.servlet.JspServlet
02:38:51.768 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@5943bd77{/webadmin,jar:file:/usr/share/neo4j/system/lib/neo4j-server-2.0.2-static-web.jar!/webadmin-html,AVAILABLE}
02:38:52.208 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@36b1f514{/db/manage,null,AVAILABLE}
02:38:52.489 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@44cdd004{/db/data,null,AVAILABLE}
02:38:52.507 [main] INFO  o.e.j.w.StandardDescriptorProcessor - NO JSP Support for /browser, did not find org.apache.jasper.servlet.JspServlet
02:38:52.508 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@9e6e47c{/browser,jar:file:/usr/share/neo4j/system/lib/neo4j-browser-2.0.2.jar!/browser,AVAILABLE}
02:38:52.632 [main] WARN  /auth - unavailable
com.sun.jersey.spi.inject.Errors$ErrorMessagesException: null
        at com.sun.jersey.spi.inject.Errors.processErrorMessages(Errors.java:170) ~[jersey-core-1.9.jar:1.9]
        at com.sun.jersey.spi.inject.Errors.postProcess(Errors.java:136) ~[jersey-core-1.9.jar:1.9]
        at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:199) ~[jersey-core-1.9.jar:1.9]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:771) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:766) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:488) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:318) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:609) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:210) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:373) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:556) ~[jersey-server-1.9.jar:1.9]
        at javax.servlet.GenericServlet.init(GenericServlet.java:244) ~[javax.servlet-3.0.0.v201112011016.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:542) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:351) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:800) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:288) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:731) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.Server.start(Server.java:342) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.Server.doStart(Server.java:290) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:363) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:166) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:412) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:192) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:103) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:57) [neo4j-server-2.0.2.jar:2.0.2]
02:38:52.634 [main] WARN  o.e.j.u.component.AbstractLifeCycle - FAILED o.e.j.s.ServletContextHandler@4c1802de{/auth,null,STARTING}: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-286950539@cdf5eca3==org.neo4j.server.web.NeoServletContainer,-1,false
javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-286950539@cdf5eca3==org.neo4j.server.web.NeoServletContainer,-1,false
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:563) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:351) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:800) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:288) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:731) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.Server.start(Server.java:342) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.Server.doStart(Server.java:290) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:363) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:166) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:412) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:192) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:103) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:57) [neo4j-server-2.0.2.jar:2.0.2]
Caused by: com.sun.jersey.spi.inject.Errors$ErrorMessagesException: null
        at com.sun.jersey.spi.inject.Errors.processErrorMessages(Errors.java:170) ~[jersey-core-1.9.jar:1.9]
        at com.sun.jersey.spi.inject.Errors.postProcess(Errors.java:136) ~[jersey-core-1.9.jar:1.9]
        at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:199) ~[jersey-core-1.9.jar:1.9]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:771) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:766) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:488) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:318) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:609) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:210) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:373) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:556) ~[jersey-server-1.9.jar:1.9]
        at javax.servlet.GenericServlet.init(GenericServlet.java:244) ~[javax.servlet-3.0.0.v201112011016.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:542) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        ... 21 common frames omitted
02:38:52.634 [main] WARN  o.e.j.u.component.AbstractLifeCycle - FAILED org.eclipse.jetty.server.handler.HandlerList@3c6463d9: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-286950539@cdf5eca3==org.neo4j.server.web.NeoServletContainer,-1,false
javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-286950539@cdf5eca3==org.neo4j.server.web.NeoServletContainer,-1,false
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:563) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:351) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:800) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:288) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:731) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.Server.start(Server.java:342) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.Server.doStart(Server.java:290) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:363) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:166) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:412) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:192) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:103) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:57) [neo4j-server-2.0.2.jar:2.0.2]
Caused by: com.sun.jersey.spi.inject.Errors$ErrorMessagesException: null
        at com.sun.jersey.spi.inject.Errors.processErrorMessages(Errors.java:170) ~[jersey-core-1.9.jar:1.9]
        at com.sun.jersey.spi.inject.Errors.postProcess(Errors.java:136) ~[jersey-core-1.9.jar:1.9]
        at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:199) ~[jersey-core-1.9.jar:1.9]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:771) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:766) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:488) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:318) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:609) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:210) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:373) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:556) ~[jersey-server-1.9.jar:1.9]
        at javax.servlet.GenericServlet.init(GenericServlet.java:244) ~[javax.servlet-3.0.0.v201112011016.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:542) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        ... 21 common frames omitted
02:38:52.635 [main] WARN  o.e.j.u.component.AbstractLifeCycle - FAILED org.eclipse.jetty.server.Server@62d75a88: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-286950539@cdf5eca3==org.neo4j.server.web.NeoServletContainer,-1,false
javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-286950539@cdf5eca3==org.neo4j.server.web.NeoServletContainer,-1,false
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:563) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:351) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:800) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:288) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:731) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.Server.start(Server.java:342) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.server.Server.doStart(Server.java:290) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
        at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:363) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:166) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:412) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:192) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:103) [neo4j-server-2.0.2.jar:2.0.2]
        at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:57) [neo4j-server-2.0.2.jar:2.0.2]
Caused by: com.sun.jersey.spi.inject.Errors$ErrorMessagesException: null
        at com.sun.jersey.spi.inject.Errors.processErrorMessages(Errors.java:170) ~[jersey-core-1.9.jar:1.9]
        at com.sun.jersey.spi.inject.Errors.postProcess(Errors.java:136) ~[jersey-core-1.9.jar:1.9]
        at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:199) ~[jersey-core-1.9.jar:1.9]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:771) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:766) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:488) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:318) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:609) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:210) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:373) ~[jersey-server-1.9.jar:1.9]
        at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:556) ~[jersey-server-1.9.jar:1.9]
        at javax.servlet.GenericServlet.init(GenericServlet.java:244) ~[javax.servlet-3.0.0.v201112011016.jar:na]
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:542) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
        ... 21 common frames omitted
2014-04-15 00:38:52.636+0000 INFO  [API] Failed to start Neo Server on port [7474], reason [javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-286950539@cdf5eca3==org.neo4j.server.web.NeoServletContainer,-1,false]
```

```
neo4j.0.0.log
```

```
Apr 15, 2014 2:38:51 AM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
Information: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
Apr 15, 2014 2:38:52 AM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
Information: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
Apr 15, 2014 2:38:52 AM com.sun.jersey.api.core.PackagesResourceConfig init
Information: Scanning for root resource and provider classes in the packages:
  org.neo4j.server.extension.auth
Apr 15, 2014 2:38:52 AM com.sun.jersey.api.core.ScanningResourceConfig logClasses
Information: Root resource classes found:
  class org.neo4j.server.extension.auth.AuthenticationResource
Apr 15, 2014 2:38:52 AM com.sun.jersey.api.core.ScanningResourceConfig init
Information: No provider classes found.
Apr 15, 2014 2:38:52 AM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
Information: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
Apr 15, 2014 2:38:52 AM com.sun.jersey.spi.inject.Errors processErrorMessages
Schwerwiegend: The following errors and warnings have been detected with resource and/or provider classes:
  SEVERE: Missing dependency for constructor public org.neo4j.server.extension.auth.AuthenticationResource(org.neo4j.server.extension.auth.MultipleAuthenticationService) at parameter index 0
```

Has somebody an idea how to fix this?

I don't want to run the Neo4j server without authentication. In the worst case I have to configure a reverse proxy.

**Comment by jexp** [comment]
Yes, the API changed. I would recommend a reverse proxy anyway as this extension is destined to break with many server updates.

**Comment by hoffmaaxe** [comment]
It is too bad that the Neo4j Server has no build-in authentication like MySQL or ArangoDB. Undeniably, it is a very nice graph database. But the missing (simple) authentication is a mess.

**Comment by jexp** [comment]
Should work now with the latest git update, please check

**Comment by hoffmaaxe** [comment]
Can you please upload a updated jar to the wiki? Thank you very much

**Comment by Jesterovskiy** [comment]
Same problem, I download authentication-extension-2.0.0-1.0-SNAPSHOT.jar - this is not worked for me. I join previous request - can you upload a updated jar? Big thanks

**Comment by jexp** [comment]
http://dist.neo4j.org/authentication-extension/authentication-extension-2.0.2-1.0-SNAPSHOT.jar

**Comment by Jesterovskiy** [comment]
:+1: It works! Thank you =)

**Comment by hoffmaaxe** [comment]
Thank you! Works great again!

**Comment by ksiomelo** [comment]
+1 thanks!

**Comment by tomekn** [comment]
Might be useful to remove the link for the jar that doesn't work anymore!

but +1, thanks nonetheless.

**Comment by superseoworld** [comment]
thx works!!!

**Comment by pavanIntel** [comment]
I updated authentication-extension-2.0.2-1.0-SNAPSHOT.jar and added   following lines in neo4j-server.properties file,
                  org.neo4j.server.credentials=username:password
                  org.neo4j.server.thirdparty_jaxrs_classes=org.neo4j.server.extension.auth=/auth

still  i'm getting error as follows :
        Starting Neo4j Server failed: missing master-credentials in neo4j-server.properties
        org.neo4j.server.ServerStartupException: Starting Neo4j Server failed: missing master-credentials           in neo4j-server.properties
