### ISSUE TITLE
'ErrorMessagesException: null' when starting Neo after adding authentication-extension

### ISSUE THREAD

**Issue by mbmihura** [neo4j-contrib/authentication-extension#34]
Hello.
After downloading authentication-extension-2.1.5-1.0-SNAPSHOT.jar, dropping it into /plugins and adding the 2 config lines to neo4j-server.properties, neo fails to start. Searching in logs file I found the following error. Any clue about what is it happening? 
Thanks.

Stacktrace:

```
2015-01-22 20:47:40.357+0000 INFO  [API] Starting HTTP on port :7474 with 40 threads available
2015-01-22 20:47:40.714+0000 INFO  [API] Enabling HTTPS on port :7473
2015-01-22 20:47:40.921+0000 INFO  [API] Mounted discovery module at [/]
2015-01-22 20:47:40.942+0000 INFO  [API] Mounted REST API at [/db/data/]
2015-01-22 20:47:40.946+0000 INFO  [API] Mounted management API at [/db/manage/]
2015-01-22 20:47:40.947+0000 INFO  [API] Mounted third-party JAX-RS package [org.neo4j.server.extension.auth] at [/auth]
2015-01-22 20:47:40.947+0000 INFO  [API] Mounted webadmin at [/webadmin]
2015-01-22 20:47:40.948+0000 INFO  [API] Mounted Neo4j Browser at [/browser]
2015-01-22 20:47:41.039+0000 INFO  [API] Mounting static content at [/webadmin] from [webadmin-html]
2015-01-22 20:47:41.142+0000 INFO  [API] Mounting static content at [/browser] from [browser]
17:47:41.145 [main] WARN  o.e.j.server.handler.ContextHandler - o.e.j.s.ServletContextHandler@1679cc1{/,null,null} contextPath ends with /
17:47:41.145 [main] WARN  o.e.j.server.handler.ContextHandler - Empty contextPath
17:47:41.147 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.0.5.v20130815
17:47:41.205 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.h.MovedContextHandler@ed62af{/,null,AVAILABLE}
17:47:41.342 [main] INFO  o.e.j.w.StandardDescriptorProcessor - NO JSP Support for /webadmin, did not find org.apache.jasper.servlet.JspServlet
17:47:41.360 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@15692fe{/webadmin,jar:file:/usr/share/neo4j/system/lib/neo4j-server-2.1.5-static-web.jar!/webadmin-html,AVAILABLE}
17:47:42.019 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@1f908dd{/db/manage,null,AVAILABLE}
17:47:42.417 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@799078{/db/data,null,AVAILABLE}
17:47:42.442 [main] INFO  o.e.j.w.StandardDescriptorProcessor - NO JSP Support for /browser, did not find org.apache.jasper.servlet.JspServlet
17:47:42.443 [main] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@e02577{/browser,jar:file:/usr/share/neo4j/system/lib/neo4j-browser-2.1.5.jar!/browser,AVAILABLE}
17:47:42.757 [main] WARN  /auth - unavailable
com.sun.jersey.spi.inject.Errors$ErrorMessagesException: null
    at com.sun.jersey.spi.inject.Errors.processErrorMessages(Errors.java:170) ~[jersey-core-1.9.jar:1.9]
    at com.sun.jersey.spi.inject.Errors.postProcess(Errors.java:136) ~[jersey-core-1.9.jar:1.9]
    at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:199) ~[jersey-core-1.9.jar:1.9]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:771) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:766) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:488) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:318) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:609) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:210) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:373) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:556) ~[jersey-server-1.9.jar:1.9]
    at javax.servlet.GenericServlet.init(GenericServlet.java:244) ~[javax.servlet-3.0.0.v201112011016.jar:na]
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:542) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:351) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:800) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:288) [jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:731) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.Server.start(Server.java:342) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.Server.doStart(Server.java:290) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:375) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:178) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:432) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:193) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:108) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:62) [neo4j-server-2.1.5.jar:2.1.5]
17:47:42.759 [main] WARN  o.e.j.u.component.AbstractLifeCycle - FAILED o.e.j.s.ServletContextHandler@3fdcbf{/auth,null,STARTING}: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-15160490@7b7d47b8==org.neo4j.server.web.NeoServletContainer,-1,false
javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-15160490@7b7d47b8==org.neo4j.server.web.NeoServletContainer,-1,false
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:563) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:351) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:800) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:288) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:731) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.Server.start(Server.java:342) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.Server.doStart(Server.java:290) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:375) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:178) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:432) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:193) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:108) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:62) [neo4j-server-2.1.5.jar:2.1.5]
Caused by: com.sun.jersey.spi.inject.Errors$ErrorMessagesException: null
    at com.sun.jersey.spi.inject.Errors.processErrorMessages(Errors.java:170) ~[jersey-core-1.9.jar:1.9]
    at com.sun.jersey.spi.inject.Errors.postProcess(Errors.java:136) ~[jersey-core-1.9.jar:1.9]
    at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:199) ~[jersey-core-1.9.jar:1.9]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:771) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:766) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:488) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:318) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:609) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:210) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:373) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:556) ~[jersey-server-1.9.jar:1.9]
    at javax.servlet.GenericServlet.init(GenericServlet.java:244) ~[javax.servlet-3.0.0.v201112011016.jar:na]
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:542) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    ... 21 common frames omitted
17:47:42.760 [main] WARN  o.e.j.u.component.AbstractLifeCycle - FAILED org.eclipse.jetty.server.handler.HandlerList@b5a08d: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-15160490@7b7d47b8==org.neo4j.server.web.NeoServletContainer,-1,false
javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-15160490@7b7d47b8==org.neo4j.server.web.NeoServletContainer,-1,false
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:563) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:351) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:800) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:288) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:731) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.Server.start(Server.java:342) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.Server.doStart(Server.java:290) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:375) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:178) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:432) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:193) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:108) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:62) [neo4j-server-2.1.5.jar:2.1.5]
Caused by: com.sun.jersey.spi.inject.Errors$ErrorMessagesException: null
    at com.sun.jersey.spi.inject.Errors.processErrorMessages(Errors.java:170) ~[jersey-core-1.9.jar:1.9]
    at com.sun.jersey.spi.inject.Errors.postProcess(Errors.java:136) ~[jersey-core-1.9.jar:1.9]
    at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:199) ~[jersey-core-1.9.jar:1.9]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:771) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:766) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:488) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:318) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:609) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:210) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:373) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:556) ~[jersey-server-1.9.jar:1.9]
    at javax.servlet.GenericServlet.init(GenericServlet.java:244) ~[javax.servlet-3.0.0.v201112011016.jar:na]
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:542) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    ... 21 common frames omitted
17:47:42.761 [main] WARN  o.e.j.u.component.AbstractLifeCycle - FAILED org.eclipse.jetty.server.Server@3f99c1: javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-15160490@7b7d47b8==org.neo4j.server.web.NeoServletContainer,-1,false
javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-15160490@7b7d47b8==org.neo4j.server.web.NeoServletContainer,-1,false
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:563) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:351) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:800) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:288) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:731) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:108) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.Server.start(Server.java:342) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:90) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:58) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.server.Server.doStart(Server.java:290) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
    at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:375) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:178) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.AbstractNeoServer.startWebServer(AbstractNeoServer.java:432) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:193) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:108) [neo4j-server-2.1.5.jar:2.1.5]
    at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:62) [neo4j-server-2.1.5.jar:2.1.5]
Caused by: com.sun.jersey.spi.inject.Errors$ErrorMessagesException: null
    at com.sun.jersey.spi.inject.Errors.processErrorMessages(Errors.java:170) ~[jersey-core-1.9.jar:1.9]
    at com.sun.jersey.spi.inject.Errors.postProcess(Errors.java:136) ~[jersey-core-1.9.jar:1.9]
    at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:199) ~[jersey-core-1.9.jar:1.9]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:771) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:766) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:488) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:318) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:609) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:210) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:373) ~[jersey-server-1.9.jar:1.9]
    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:556) ~[jersey-server-1.9.jar:1.9]
    at javax.servlet.GenericServlet.init(GenericServlet.java:244) ~[javax.servlet-3.0.0.v201112011016.jar:na]
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:542) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
    ... 21 common frames omitted
2015-01-22 20:47:42.761+0000 INFO  [API] Failed to start Neo Server on port [7474], reason [javax.servlet.ServletException: org.neo4j.server.web.NeoServletContainer-15160490@7b7d47b8==org.neo4j.server.web.NeoServletContainer,-1,false]
```

**Comment by jexp** [comment]
What did you add to the config?

**Comment by mbmihura** [comment]
The following lines, I took them from Readme.md:

org.neo4j.server.credentials=username:password
org.neo4j.server.thirdparty_jaxrs_classes=org.neo4j.server.extension.auth=/auth
