### ISSUE TITLE
NoSuchMethodError: org.neo4j.server.configuration.Configurator.getThirdpartyJaxRsClasses()Ljava/util/Set

### ISSUE THREAD

**Issue by scdicks** [neo4j-contrib/authentication-extension#7]
I'm trying to set up neo4j on Amazon ECS.  The template is failing to pull the Oracle JVM, so I manually installed OpenJDK and neo4j 1.9.2.

Then after installing the authentication extension and restarting neo4j, I get this error:

23:07:19.935 [main] WARN  o.neo4j.kernel.EmbeddedGraphDatabase - WARNING! You are using an unsupported Java runtime. Please use Oracle(R) Java(TM) Runtime Environment 7.
7/24/13 11:07:20 PM org.neo4j.server.database.Database INFO: Successfully started database
7/24/13 11:07:20 PM org.neo4j.server.AbstractNeoServer INFO: Starting Neo Server on port [7474] with [20] threads available
7/24/13 11:07:21 PM org.neo4j.server.AbstractNeoServer INFO: Enabling HTTPS on port [7473]
7/24/13 11:07:21 PM org.neo4j.server.modules.DiscoveryModule INFO: Mounted discovery module at [/]
7/24/13 11:07:21 PM org.neo4j.server.plugins.PluginManager INFO: Loaded server plugin "CypherPlugin"
7/24/13 11:07:21 PM org.neo4j.server.plugins.PluginManager INFO: Loaded server plugin "GremlinPlugin"
7/24/13 11:07:21 PM org.neo4j.server.modules.RESTApiModule INFO: Mounted REST API at [/db/data/]
7/24/13 11:07:21 PM org.neo4j.server.modules.ManagementApiModule INFO: Mounted management API at [/db/manage/]
7/24/13 11:07:21 PM org.neo4j.server.extension.auth.AuthenticationExtensionInitializer INFO: START class org.neo4j.server.extension.auth.AuthenticationExtensionInitializer
7/24/13 11:07:21 PM org.neo4j.server.CommunityBootstrapper SEVERE: 
org.neo4j.server.ServerStartupException: Starting neo server failed, see nested exception.
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:214)
    at org.neo4j.server.Bootstrapper.start(Bootstrapper.java:86)
    at org.neo4j.server.Bootstrapper.main(Bootstrapper.java:49)
Caused by: java.lang.NoSuchMethodError: org.neo4j.server.configuration.Configurator.getThirdpartyJaxRsClasses()Ljava/util/Set;
    at org.neo4j.server.extension.auth.AuthenticationExtensionInitializer.getMyMountpoint(AuthenticationExtensionInitializer.java:100)
    at org.neo4j.server.extension.auth.AuthenticationExtensionInitializer.start(AuthenticationExtensionInitializer.java:81)
    at org.neo4j.server.modules.ExtensionInitializer.initializePackages(ExtensionInitializer.java:60)
    at org.neo4j.server.modules.ThirdPartyJAXRSModule.start(ThirdPartyJAXRSModule.java:61)
    at org.neo4j.server.AbstractNeoServer.startModules(AbstractNeoServer.java:258)
    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:181)
    ... 2 more
7/24/13 11:07:21 PM org.neo4j.server.CommunityBootstrapper SEVERE: Failed to start Neo Server on port [7474]

**Comment by anassirk** [comment]
got the same problem here.

**Comment by simpsonjulian** [comment]
Thanks for reporting that guys, we'll get onto it.

**Comment by glsignal** [comment]
I figure you've found this already, but should that method name really have changed on a minor release?

[1.9.1](http://components.neo4j.org/neo4j-server/1.9.1/apidocs/org/neo4j/server/configuration/Configurator.html#method_summary) vs. [1.9.2](http://components.neo4j.org/neo4j-server/1.9.2/apidocs/org/neo4j/server/configuration/Configurator.html#method_summary)

**Comment by jexp** [comment]
good point, it shouldn't

**Comment by glsignal** [comment]
I've made the necessary(?) changes to have the library build against 1.9.2 over on [my fork](https://github.com/glsignal/authentication-extension/commit/4329a4c39a80721ed7b5c989ee1318c1f4b4fafe)

Edit: Kudos for making it so easy to build, by the way

**Comment by jexp** [comment]
Can you issue a PR against the 1.9 branch? That would be great. Thanks so much.

**Comment by glsignal** [comment]
Sure thing.

**Comment by ghost** [comment]
Does http://dist.neo4j.org.s3.amazonaws.com/authentication-extension/authentication-extension-1.9-SNAPSHOT-1.0-SNAPSHOT.jar actually contain the fix?

**Comment by glsignal** [comment]
I'm unsure; if it were a maven build it should be tagged 1.9.2 rather than 1.9.

[Here's](https://copy.com/Xy4i0Zr09YAA) a build I've done if you want to use it until a maintainer posts one.
